version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: "Dockerfile"
    stdin_open: true
    volumes:
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      dockerfile: "Dockerfile"
    volumes:
      - ./api/src:/app/src
    environment:
      - MONGO_URI="mongodb://mongo:27017"
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  dbseed:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    links:
      - mongo
